### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Xunyan2018** [koishijs/koishi-plugin-twdne#1]
2023 -08 -2513:51:45 [W] command twdne
Error: read ECONNRESET
at Function. AxiosError. from 
(C: \Users \Administrator\AppData\Roaming \Koi shi\Desktop\data\instances \default\node_ modules \axios\dist\node\axios . cjs:836:14)
at RedirectableRequest. handleReques tError
(C: \users \Administrator\AppData Roaming \Koi shi \Desktop \data\instances \def ault \node_ modules \axios \dist \node\axios . cjs:3010:25)
at RedirectableRequest . emit (node :event:513:28)
at ClientRequest . eventHandlers. <computed>
(C: \Users \Administrator\AppData\Roaming \Koi shi\Desktop\data\instances \default\node_ modules \follow-redirects\index. js:14:24)
at ClientRequest . emit (node :events:513:28)
at TLSSocket . socketErrorListener (node:_ http_ client : 494:9)
at TLSSocket. emit ( node: events :513:28)
at emitErrorNT (node: internal/streams/ destroy :157:8)
st emitErrorCloseNT (node: internal/ streams/ destroy:122:3)
at processTicksAndRejections (node : internal/ process/task queues: 83:21)

**Comment by shigma** [comment]
请切换更好的网络环境。

**Comment by Xunyan2018** [comment]
> 请切换更好的网络环境。

你好，无论如何更换网络环境均无效

**Comment by ilharp** [comment]
![image](https://github.com/koishijs/koishi-plugin-twdne/assets/20179549/2159a519-a68f-4973-91a0-53b70185034a)

我刚刚进行了测试，是有效的

环境：Koishi 最新，网络移动宽带直连

如果你已解决此问题或不再需要此问题，那么可以关闭此 issue。
